### ISSUE TITLE
Claim for AMX mined on invalid chain since block 109740  (Order No. 9)

### ISSUE THREAD

**Issue by klomar141** [Armor-Network/AMX-fund#1]
![image](https://user-images.githubusercontent.com/89179628/130013894-b22c84e2-ef0d-474e-8d62-2e6a9776309d.png)
[https://discord.com/channels/867527064500305970/872054689817042974/873691368730529793](url)

**Transactions:**  
[amx1ofP5bCKGPbiXbRmwSjbnSkXccMwSAHMdxppCaJvMEZ8mXLYki9j2LwLCR3gpZ4PsBgMW3pHno1Dh7XyZnAFj4yiZ2vm1E7.txt](https://github.com/Armor-Network/AMX-fund/files/7013451/amx1ofP5bCKGPbiXbRmwSjbnSkXccMwSAHMdxppCaJvMEZ8mXLYki9j2LwLCR3gpZ4PsBgMW3pHno1Dh7XyZnAFj4yiZ2vm1E7.txt)

**Amount:** 545.97029 AMX
**Received Address:** amx1ofP5bCKGPbiXbRmwSjbnSkXccMwSAHMdxppCaJvMEZ8mXLYki9j2LwLCR3gpZ4PsBgMW3pHno1Dh7XyZnAFj4yiZ2vm1E7
**Payout Address:** amx1ofP5bCKGPbiXbRmwSjbnSkXccMwSAHMdxppCaJvMEZ8mXLYki9j2LwLCR3gpZ4PsBgMW3pHno1Dh7XyZnAFj4yiZ2vm1E7
**Mining pool:** pool.armornetwork.org

**Comment by username1565** [comment]
The file, by link inside the screen, was been saved.
See attachment:
[saved as html page.zip](https://github.com/Armor-Network/AMX-fund/files/7018374/saved.as.html.page.zip)

**Comment by username1565** [comment]
@klomar141 , the file, by link inside the screen, was been saved too.
See attachment: [saved as html page.zip](https://github.com/Armor-Network/AMX-fund/files/7018374/saved.as.html.page.zip)

**Comment by username1565** [comment]
600.00000000 AMX was been transferred, by this order:
Transaction hash: cbade74dccae5447229e29297b681359aaf3fab95731d5a2a8586d96ecb1ab56
http://radioactive.es/AMX-explorer/?search=cbade74dccae5447229e29297b681359aaf3fab95731d5a2a8586d96ecb1ab56

```
Order №:		9
Discord Username:	@klomar#4888
Amount:			545.97029000 AMX
TX-hash:		cbade74dccae5447229e29297b681359aaf3fab95731d5a2a8586d96ecb1ab56
Block-explorer-link:	http://radioactive.es/AMX-explorer/?search=cbade74dccae5447229e29297b681359aaf3fab95731d5a2a8586d96ecb1ab56
Payeer address:		amx1pBbjedF32ejBKmQ6hpZmYz1ZwgiyZE8EVWzsCY1RaayvKnpfYqUc4CJQurEHNUY5g818pEzh4MVg7SojMxiXAATF3R2maE
Payout address:		amx1ofP5bCKGPbiXbRmwSjbnSkXccMwSAHMdxppCaJvMEZ8mXLYki9j2LwLCR3gpZ4PsBgMW3pHno1Dh7XyZnAFj4yiZ2vm1E7
```
![Order9_transaction](https://user-images.githubusercontent.com/39200328/130411015-f1f78d81-207c-43b0-816b-a0769f1fe1ce.png)
